dockergalaxy/app/core/urls.py
from django.urls import path
from core.views import *

app_name = "core"

urlpatterns = [
    path('', index, name='index'),
    path('category/', category_list_view, name='category-list'),
    path('category/<title>/', category_subcategory_list_view, name='category-subcategory-list'),
    path('subcategory/<title>/', subcategory_product_list_view, name='subcategory-product-list'),
    path('product/<pid>', product_detail_view, name='product-detail'),
    path('product/', product_view, name='product'),
]

dockergalaxy/app/ecomprj/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [    
    path('admin/', admin.site.urls),
    path('', include('core.urls')),
    path('user/', include('userauths.urls')),
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

dockergalaxy/app/core/models.py
from django.db import models
# from shortuuid.django_fields import ShortUUIDField
from django.utils.safestring import mark_safe
from userauths.models import User
import uuid
# Create your models here.

STATUS_CHOICE = (
    ("process", "Processing"),
    ("shipped", "Shipped"),
    ("delivered", "Delivered"),

)

STATUS = (
    ("draft", "Draft"),
    ("disabled", "Disabled"),
    ("in_review", "In Review"),
    ("rejected", "Rejected"),
    ("published", "Published"),
)

RATING = (
    (1, "★☆☆☆☆"),
    (2, "★★☆☆☆"),
    (3, "★★★☆☆"),
    (4, "★★★★☆"),
    (5, "★★★★★"),
)


def user_directory_path(instance, filename):
    return 'user_{0}/{1}'.format(instance.user.id, filename)


class Category(models.Model):

    cid = models.UUIDField(default=uuid.uuid4, max_length=10)
    title = models.CharField(max_length=100, default="MEN")
    image = models.ImageField(upload_to='category', null=True)

    class Meta:
        verbose_name_plural = 'Categories'

    def category_image(self):
        return mark_safe('<img src="%s" width="50" height="50" />' % (self.image.url))

    def __str__(self):
        return self.title


class Subcategory(models.Model):

    scid = models.UUIDField(default=uuid.uuid4, max_length=10)
    category = models.ForeignKey(
        Category, on_delete=models.SET_NULL, null=True)
    title = models.CharField(max_length=100, default="Shirt")
    image = models.ImageField(upload_to='subcategory', null=True)

    class Meta:
        verbose_name_plural = 'Subcategories'

    def subcategory_image(self):
        return mark_safe('<img src="%s" width="50" height="50" />' % (self.image.url))

    def __str__(self):
        return self.title


class Tags(models.Model):
    pass


class Vendor(models.Model):
    vid = models.UUIDField(primary_key=True, default=uuid.uuid4, max_length=10)

    title = models.CharField(max_length=100, default="Nesify")
    image = models.ImageField(upload_to=user_directory_path,)
    description = models.TextField(null=True, blank=True, default="New vendor")

    address = models.CharField(max_length=100, default="Nepal")
    contact = models.CharField(
        max_length=100, default="+977 (123) (456) (7890)")
    chat_rspn_time = models.CharField(max_length=100, default="1 Day")
    shipping_time = models.CharField(max_length=100, default="1 Week")
    authentic_rating = models.CharField(max_length=100, default="100%")
    days_return = models.CharField(max_length=100, default="No return")
    warranty_period = models.CharField(max_length=100, default="No warranty")

    user = models.ForeignKey(User, on_delete=models.SET_NULL, null=True)

    class Meta:
        verbose_name_plural = 'Vendors'

    def vendor_image(self):
        return mark_safe('<img src="%s" width="50" height="50" />' % (self.image.url))

    def __str__(self):
        return self.title


class Product(models.Model):
    pid = models.UUIDField(primary_key=True, default=uuid.uuid4)

    user = models.ForeignKey(User, on_delete=models.SET_NULL, null=True, related_name="cat")
    category = models.ForeignKey(
        Category, on_delete=models.SET_NULL, null=True)
    subcategory = models.ForeignKey(
        Subcategory, on_delete=models.SET_NULL, null=True, related_name="subcat")
    vendor = models.ForeignKey(Vendor, on_delete=models.SET_NULL, null=True)

    title = models.CharField(max_length=100, default="new product")
    image = models.ImageField(upload_to=user_directory_path)
    description = models.TextField(
        null=True, blank=True, default="this is product")
    s_stock = models.DecimalField(max_digits=10, default=0, decimal_places=0)
    m_stock = models.DecimalField(max_digits=10, default=0, decimal_places=0)
    l_stock = models.DecimalField(max_digits=10, default=0, decimal_places=0)
    xl_stock = models.DecimalField(max_digits=10, default=0, decimal_places=0)
    xxl_stock = models.DecimalField(max_digits=10, default=0, decimal_places=0)
    price = models.DecimalField(max_digits=1000, decimal_places=2)
    old_price = models.DecimalField(max_digits=1000, decimal_places=2)

    specifications = models.TextField(null=True, blank=True)
    # tags = models.ForeignKey(Tags, on_delete=models.SET_NULL, null=True,)

    product_status = models.CharField(
        choices=STATUS, max_length=10, default="in_review")
    status = models.BooleanField(default=True)
    featured = models.BooleanField(default=False)
    digital = models.BooleanField(default=False)

    sku = models.UUIDField(default=uuid.uuid4, max_length=10)

    date = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField()

    class Meta:
        verbose_name_plural = 'Products'

    def product_image(self):
        return mark_safe('<img src="%s" width="50" height="50" />' % (self.image.url))

    def __str__(self):
        return self.title

    def get_percentage(self):
        new_price = (100 - (self.price / self.old_price) * 100)
        return new_price

    def get_price(self):
        discount_price = self.old_price - self.price
        return discount_price

    def get_stock(self):
        total_stock = self.s_stock + self.m_stock + self.l_stock + self.xl_stock + self.xxl_stock
        return total_stock


class ProductImages(models.Model):
    images = models.ImageField(upload_to="product-images")
    product = models.ForeignKey(Product, on_delete=models.SET_NULL, null=True)
    date = models.DateTimeField(auto_now_add=True)

    class Meta:
        verbose_name_plural = 'Product Images'


class CartOrder(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    price = models.DecimalField(max_digits=1000, decimal_places=2)
    paid_track = models.BooleanField(default=False)
    order_date = models.DateTimeField(auto_now_add=True,)
    product_status = models.CharField(
        choices=STATUS_CHOICE, max_length=30, default="processing")

    class Meta:
        verbose_name_plural = 'Cart Order'


class CartOrderItems(models.Model):
    order = models.ForeignKey(CartOrder, on_delete=models.CASCADE)
    invoice_no = models.CharField(max_length=200)
    product_status = models.CharField(max_length=200)
    item = models.CharField(max_length=200)
    image = models.CharField(max_length=200)
    quantity = models.IntegerField(default=0)
    price = models.DecimalField(max_digits=1000, decimal_places=2)
    total = models.DecimalField(max_digits=1000, decimal_places=2)

    class Meta:
        verbose_name_plural = 'Cart Order Items'

    def order_img(self):
        return mark_safe('<img src="/media/%s" width="50" height="50" />' % (self.image))


class ProductReview(models.Model):
    user = models.ForeignKey(User, on_delete=models.SET_NULL, null=True)
    product = models.ForeignKey(Product, on_delete=models.SET_NULL, null=True)
    review = models.TextField()
    rating = models.IntegerField(choices=RATING, default=None)
    date = models.DateTimeField(auto_now_add=True)

    class Meta:
        verbose_name_plural = 'Product Reviews'

    def __str__(self):
        return self.product

    def get_rating(self):
        return self.rating


class wishlist(models.Model):
    user = models.ForeignKey(User, on_delete=models.SET_NULL, null=True)
    product = models.ForeignKey(Product, on_delete=models.SET_NULL, null=True)
    date = models.DateTimeField(auto_now_add=True)

    class Meta:
        verbose_name_plural = 'Wishlists'

    def __str__(self):
        return self.product


class Address(models.Model):
    user = models.ForeignKey(User, on_delete=models.SET_NULL, null=True)
    address = models.CharField(max_length=100, null=True)
    status = models.BooleanField(default=False)

    class Meta:
        verbose_name_plural = 'Address'

dockergalaxy/app/core/views.py
from django.shortcuts import render
from core.models import *
from django.db.models import Count

# Create your views here.


def index(request):
    product = Product.objects.filter(
        product_status="published", featured=True).order_by("-date")

    context = {
        'products': product,
    }

    return render(request, 'core/index.html', context)


def category_list_view(request):
    categories = Category.objects.all().annotate(product_count=Count('product'))
    context = {
        "categories": categories,
    }

    return render(request, 'core/category-list.html', context)
    

def category_subcategory_list_view(request,title):
    category = Category.objects.get(title=title)
    subcategories = Subcategory.objects.filter(category=category)

    context = {
        "category": category,
        "subcategories": subcategories,
    }

    return render(request, 'core/category-subcategory-list.html', context)

    
def subcategory_product_list_view(request,title):
    subcategory = Subcategory.objects.get(title=title)
    products = Product.objects.filter(product_status='published', subcategory=subcategory)

    context = {
        "subcategory": subcategory,
        "products": products
    }

    return render(request, 'core/subcategory-product-list.html', context)


def product_view(request):
    product = Product.objects.filter(
        product_status="published").order_by("-date")

    context = {
        'products': product,
    }

    return render(request, 'core/product.html', context)


def product_detail_view(request, pid):
    product = Product.objects.get(pid=pid)
    product_images = ProductImages.objects.all()

    context = {
        'product': product,
        'product_images': product_images,
    }

    return render(request, 'core/product-detail.html', context)

dockergalaxy/app/templates/core/category-list.html
{% extends 'partials/base.html' %}
{% load static %}

{% block content %}

<!--Body Content-->
<div id="page-content">
  <div class="container-fluid">
      <div class="row">
          <!--Main Content-->
          <div class="col-12 col-sm-12 col-md-9 col-lg-10 main-col">
              <div class="productList">
                  <!--Toolbar-->
                  <!--End Toolbar-->
                  <div class="grid-products grid--view-items">
                      <div class="row">
                        {% for category in categories %}
                          <div class="col-12 col-sm-12 col-md-6 col-lg-4 grid-view-item style2 item">
                              <div class="grid-view_image">
                                  <!-- start product image -->
                                  <a href="{% url 'core:category-subcategory-list' category.title %}" class="grid-view-item__link">
                                      <!-- image -->
                                      <img class="grid-view-item__image primary blur-up lazyload"
                                          data-src="{{ category.image.url }}"
                                          src="{{ category.image.url }}" alt="image"
                                          title="product">
                                      <!-- End image -->
                                      <!-- Hover image -->
                                      <img class="grid-view-item__image hover blur-up lazyload"
                                          data-src="{{ category.image.url }}"
                                          src="{{ category.image.url }}" alt="image"
                                          title="product">
                                      <!-- End hover image -->
                                      <div class="product-name">
                                        <br>
                                        <h3>
                                            <strong>{{ category.title }}</strong>
                                        </h3>
                                        <hr>
                                       </div>
                                  </a>
                                  <!-- end product image -->
                              </div>
                        </div>
                        {% endfor %}
                  </div>
              </div>
              <!--End Main Content-->
          </div>
      </div>
  </div>
  <!--End Body Content-->

{% endblock %}

dockergalaxy/app/templates/core/category-subcategory-list.html
{% extends 'partials/base.html' %}
{% load static %}

{% block content %}

<!--Body Content-->
<div id="page-content">
  <div class="container-fluid">
      <div class="row">
          <!--Main Content-->
          <div class="col-12 col-sm-12 col-md-9 col-lg-10 main-col">
              <div class="productList">
                  <!--Toolbar-->
                  <!--End Toolbar-->
                  <div class="grid-products grid--view-items">
                      <div class="row">
                        {% for subcategory in subcategories %}
                          <div class="col-12 col-sm-12 col-md-6 col-lg-4 grid-view-item style2 item">
                              <div class="grid-view_image">
                                  <!-- start product image -->
                                  <a href="{% url 'core:subcategory-product-list' subcategory.title %}" class="grid-view-item__link">
                                      <!-- image -->
                                      <img class="grid-view-item__image primary blur-up lazyload"
                                          data-src="{{ subcategory.image.url }}"
                                          src="{{ subcategory.image.url }}" alt="image"
                                          title="product">
                                      <!-- End image -->
                                      <!-- Hover image -->
                                      <img class="grid-view-item__image hover blur-up lazyload"
                                          data-src="{{ subcategory.image.url }}"
                                          src="{{ subcategory.image.url }}" alt="image"
                                          title="product">
                                      <!-- End hover image -->
                                      <div class="product-name">
                                        <br>
                                        <h3>
                                            <strong>{{ subcategory.title }}</strong>
                                        </h3>
                                        <hr>
                                       </div>
                                  </a>
                                  <!-- end product image -->
                              </div>
                        </div>
                        {% endfor %}
                  </div>
              </div>
              <!--End Main Content-->
          </div>
      </div>
  </div>
  <!--End Body Content-->

{% endblock %}

dockergalaxy/app/templates/core/index.html
{% extends 'partials/base.html' %}
{% load static %}

{% block content %}
  <!-- Body Content -->
  <div id="page-content">
    <!-- Home slider -->
    <div class="slideshow slideshow-wrapper pb-section">
      <div class="home-slideshow">
        <div class="slide slideshow--medium">
          <div class="blur-up lazyload">
            <img class="blur-up lazyload" data-src="{% static 'assets/images/slideshow-banners/home12-category-banner1.jpg' %}" src="{% static 'assets/images/slideshow-banners/home12-category-banner1.jpg' %}" alt="Outfit of Today" title="Outfit of Today" />
            <div class="slideshow__text-wrap slideshow__overlay classic middle">
              <div class="slideshow__text-content classic left">
                <div class="container">
                  <div class="wrap-caption left">
                    <a href="{% url 'core:category-list' %}"><h2 class="h1 mega-title slideshow__title" style="color:#333;">Outfit of Today</h2></a>
                    <span class="mega-subtitle slideshow__subtitle" style="color:#333;">Lookbook ss 2018</span>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
        <div class="slide slideshow--medium">
          <div class="blur-up lazyload">
            <img class="blur-up lazyload" data-src="{% static 'assets/images/slideshow-banners/home12-category-banner2.jpg' %}" src="{% static 'assets/images/slideshow-banners/home12-category-banner2.jpg' %}" alt="Accessories" title="Accessories" />
            <div class="slideshow__text-wrap slideshow__overlay classic middle">
              <div class="slideshow__text-content classic left">
                <div class="container">
                  <div class="wrap-caption left">
                    <h2 class="h1 mega-title slideshow__title" style="color:#333;">Accessories</h2>
                    <span class="mega-subtitle slideshow__subtitle" style="color:#333;">New Collection A-W ss18</span>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
    <!-- End Home slider -->
  </div>
  <!-- End Body Content -->

  <div class="d-grid gap-2" style="padding-left: 10px; padding-right: 10px;">
    <a href="{% url 'core:category-list' %}" class="btn btn-info" role="button">Shop By Categories</a>
  </div>

  <!-- Collection Tab slider -->
  <div class="tab-slider-product section">
    <div class="container">
      <div class="row">
        <div class="col-12 col-sm-12 col-md-12 col-lg-12">
          <div class="tabs-listing">
            <div class="tab_container">
              <div class="section-header text-center">
                <h2 class="h2">New Arrivals</h2>
                <p>Browse the huge variety of our products</p>
              </div>
              <br />
              <div id="tab2" class="tab_content grid-products">
                <div class="productSlider">
                  {% for product in products %}
                    {% if product.price == product.old_price and product.get_stock > 0 %}
                      <div class="col-12 item">
                        <!-- start product image -->
                        <div class="product-image">
                          <!-- start product image -->
                          <a href="{% url 'core:product-detail' product.pid %}">
                            <!-- image -->
                            <img class="primary blur-up lazyload" data-src="{{ product.image.url }}" src="{{ product.image.url }}" alt="image" title="product" />
                            <!-- End image -->
                            <!-- Hover image -->
                            <img class="hover blur-up lazyload" data-src="{{ product.image.url }}" src="{{ product.image.url }}" alt="image" title="product" />
                            <!-- End hover image -->

                            <div class="product-labels rectangular">
                              <span class="lbl pr-label1">HOT</span>
                            </div>
                          </a>
                          <!-- end product image -->

                          <!-- Start product button -->
                          <form class="variants add" action="#" onclick="window.location.href='cart.html'" method="post">
                            <button class="btn btn-addto-cart" type="button" tabindex="0">Add To Cart</button>
                          </form>
                          <div class="button-set">
                            <div class="wishlist-btn">
                              <a class="wishlist add-to-wishlist" href="wishlist.html"><i class="icon anm anm-heart-l"></i></a>
                            </div>
                          </div>
                          <!-- end product button -->
                        </div>
                        <!-- end product image -->

                        <!-- start product details -->
                        <div class="product-details text-center">
                          <!-- product name -->
                          <div class="product-name">
                            <a href="{% url 'core:product-detail' product.pid %}">{{ product.title }}</a>
                          </div>
                          <div class="product-name">
                            <span class="price">Size {{ product.size }}</span>
                          </div>
                          <!-- End product name -->
                          <!-- product price -->
                          <div class="product-price">
                            <span class="price">RS {{ product.price }}</span>
                          </div>
                          <div class="product-name">
                            <a href="short-description.html"><strong>By</strong> {{ product.vendor.title }}</a>
                          </div>
                          <!-- End product price -->
                          <div class="product-review">
                            <i class="font-13 fa fa-star"></i>
                            <i class="font-13 fa fa-star"></i>
                            <i class="font-13 fa fa-star"></i>
                            <i class="font-13 fa fa-star"></i>
                            <i class="font-13 fa fa-star"></i>
                          </div>
                        </div>
                        <!-- End product details -->
                      </div>
                    {% endif %}
                  {% endfor %}
                </div>
                <hr />
                <div class="section-header text-center">
                  <h2 class="h2">HUGE DISCOUNTS</h2>
                  <p>See what we have on our sales section</p>
                </div>
                <br />
                <div class="productSlider">
                  {% for product in products %}
                    {% if product.price != product.old_price and product.get_stock > 0  %}
                      <div class="col-12 item">
                        <!-- start product image -->
                        <div class="product-image">
                          <!-- start product image -->
                          <a href="{% url 'core:product-detail' product.pid %}">
                            <!-- image -->
                            <img class="primary blur-up lazyload" data-src="{{ product.image.url }}" src="{{ product.image.url }}" alt="image" title="product" />
                            <!-- End image -->
                            <!-- Hover image -->
                            <img class="hover blur-up lazyload" data-src="{{ product.image.url }}" src="{{ product.image.url }}" alt="image" title="product" />
                            <!-- End hover image -->

                            <div class="product-labels rectangular">
                              <span class="lbl on-sale">{{ product.get_percentage|floatformat:0 }}%</span> <span class="lbl pr-label1">SALE</span>
                            </div>
                          </a>
                          <!-- end product image -->

                          <!-- Start product button -->
                          <form class="variants add" action="#" onclick="window.location.href='cart.html'" method="post">
                            <button class="btn btn-addto-cart" type="button" tabindex="0">Add To Cart</button>
                          </form>
                          <div class="button-set">
                            <div class="wishlist-btn">
                              <a class="wishlist add-to-wishlist" href="wishlist.html"><i class="icon anm anm-heart-l"></i></a>
                            </div>
                          </div>
                          <!-- end product button -->
                        </div>
                        <!-- end product image -->

                        <!-- start product details -->
                        <div class="product-details text-center">
                          <!-- product name -->
                          <div class="product-name">
                            <a href="{% url 'core:product-detail' product.pid %}">{{ product.title }}</a>
                          </div>
                          <div class="product-name">
                            <span class="price">Size {{ product.size }}</span>
                          </div>
                          <!-- End product name -->
                          <!-- product price -->
                          <div class="product-price">
                            {% if product.price != product.old_price %}
                              <span class="old-price">RS {{ product.old_price }}</span>
                            {% endif %}
                            <span class="price">RS {{ product.price }}</span>
                          </div>
                          <div class="product-name">
                            <a href="short-description.html"><strong>By</strong> {{ product.vendor.title }}</a>
                          </div>
                          <!-- End product price -->
                          <div class="product-review">
                            <i class="font-13 fa fa-star"></i>
                            <i class="font-13 fa fa-star"></i>
                            <i class="font-13 fa fa-star"></i>
                            <i class="font-13 fa fa-star"></i>
                            <i class="font-13 fa fa-star"></i>
                          </div>
                        </div>
                        <!-- End product details -->
                      </div>
                    {% endif %}
                  {% endfor %}
                </div>
                <hr />
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>

  <!-- Store Feature -->
  <div class="store-feature section">
    <div class="container">
      <div class="row">
        <div class="col-12 col-sm-12 col-md-12 col-lg-12">
          <ul class="display-table store-info">
            <li class="display-table-cell">
              <i class="icon anm anm-truck-l"></i>
              <h5>Shipping</h5>
              <span class="sub-text">Shipping all over Nepal</span>
            </li>
            <li class="display-table-cell">
              <i class="icon anm anm-dollar-sign-r"></i>
              <h5>Awesome Sales</h5>
              <span class="sub-text">Get mega discounts</span>
            </li>
            <li class="display-table-cell">
              <i class="icon anm anm-comments-l"></i>
              <h5>Online Support</h5>
              <span class="sub-text">We support online 24/7 on day</span>
            </li>
            <li class="display-table-cell">
              <i class="icon anm anm-credit-card-front-r"></i>
              <h5>Easy Payments</h5>
              <span class="sub-text">All payment are Secured and trusted.</span>
            </li>
          </ul>
        </div>
      </div>
    </div>
  </div>
  <!-- End Store Feature -->
{% endblock %}