dockergalaxy/app/core/urls.py
from django.urls import path
from core.views import *

app_name = "core"

urlpatterns = [
    path('', index, name='index'),
    path('category/', category_list_view, name='category-list'),
    path('category/<title>/', category_subcategory_list_view, name='category-subcategory-list'),
    path('subcategory/<title>/', subcategory_product_list_view, name='subcategory-product-list'),
    path('product/<pid>', product_detail_view, name='product-detail'),
    path('product/', product_view, name='product'),
]

dockergalaxy/app/ecomprj/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [    
    path('admin/', admin.site.urls),
    path('', include('core.urls')),
    path('user/', include('userauths.urls')),
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

dockergalaxy/app/userauths/urls.py
from django.urls import path
from userauths import views

app_name = "userauths"

urlpatterns = [
    path('sign-up/', views.register_view, name='sign-up'),
    path('sign-in/', views.login_view, name='sign-in'),
    path('sign-out/', views.logout_view, name='sign-out'),
]

dockergalaxy/app/templates/partials/base.html
{% load static %}

<!DOCTYPE html>
<html class="no-js" lang="en">
  <head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta http-equiv="x-ua-compatible" content="ie=edge" />
    <title>kushal store</title>
    <meta name="description" content="description" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <!-- Favicon -->
    <link rel="shortcut icon" href="assets/images/favicon.png" />
    <!-- Plugins CSS -->
    <link rel="stylesheet" href="{% static 'assets/css/plugins.css' %}" />
    <!-- Bootstap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous" />
    <link rel="stylesheet" href="{% static 'assets/css/bootstrap.min.css' %}" />
    <!-- Main Style CSS -->
    <link rel="stylesheet" href="{% static 'assets/css/style.css' %}" />
    <link rel="stylesheet" href="{% static 'assets/css/responsive.css' %}" /> 
    {% comment %} <style>
      .footer {
         position: fixed;
         left: 0;
         bottom: 0;
         width: 100%;
         background-color: red;
         color: white;
         text-align: center;
         margin-top: 10%;
      }
      </style> {% endcomment %}
  </head>
  <body class="template-index belle home6-modern">
    <div id="pre-loader">
      <img src="{% static 'assets/images/loader.gif' %}" alt="Loading..." />
    </div>
    <div class="pageWrapper">
      <!-- Search Form Drawer -->
      <div class="search">
        <div class="search__form">
          <form class="search-bar__form" action="#">
            <button class="go-btn search__button" type="submit"><i class="icon anm anm-search-l"></i></button>
            <input class="search__input" type="search" name="q" value="" placeholder="Search entire store..." aria-label="Search" autocomplete="off" />
          </form>
          <button type="button" class="search-trigger close-btn"><i class="anm anm-times-l"></i></button>
        </div>
      </div>
      <!-- End Search Form Drawer -->

      <!-- Header -->
      <div class="top-header" style="background-color: #333;">
        <div class="container-fluid">
          <div class="row">
            <div class="col-10 col-sm-8 col-md-5 col-lg-4">
              <p class="phone-no">
                <i class="anm anm-phone-s"></i>Customer service: 982-8866-501
              </p>
            </div>
            <div class="col-sm-4 col-md-4 col-lg-8 d-none d-lg-none d-md-block d-lg-block">
              <div class="text-center"></div>
            </div>
            <div class="col-2 col-sm-4 col-md-3 col-lg-8 text-right">
              <span class="user-menu d-block d-lg-none"><i class="anm anm-user-al" aria-hidden="true"></i></span>
              <ul class="customer-links list-inline">
                {% if request.user.is_authenticated %}
                  <li>
                    <a href="{% url 'userauths:sign-out' %}">Logout</a>
                  </li>
                  <li>
                    <a href="wishlist.html">Wishlist</a>
                  </li>
                {% else %}
                  <li>
                    <a href="{% url 'userauths:sign-in' %}">Login</a>
                  </li>
                  <li>
                    <a href="{% url 'userauths:sign-up' %}">Create Account</a>
                  </li>
                {% endif %}
              </ul>
            </div>
          </div>
        </div>
      </div>
      <!-- End Header -->

      <!-- Desktop view -->
      <div class="header-wrap animated d-flex border-bottom">
        <div class="container-fluid">
          <div class="row align-items-center">
            <!-- Desktop Logo -->
            <div class="logo col-md-2 col-lg-2 d-none d-lg-block">
              <a href="{% url 'core:index' %}"><img src="{% static 'assets/images/logo.svg' %}" alt="Belle Multipurpose Html Template" title="Belle Multipurpose Html Template" /></a>
            </div>
            <!-- End Desktop Logo -->
            <div class="col-2 col-sm-3 col-md-3 col-lg-8">
              <div class="d-block d-lg-none">
                <button type="button" class="btn--link site-header__menu js-mobile-nav-toggle mobile-nav--open">
                  <i class="icon anm anm-times-l"></i>
                  <i class="anm anm-bars-r"></i>
                </button>
              </div>
              <!-- Desktop Menu -->
              <nav class="grid__item" id="AccessibleNav">
                <!-- for mobile -->
                <ul id="siteNav" class="site-nav medium center hidearrow">
                  <li class="lvl1 parent megamenu">
                    <a href="{% url 'core:index' %}">Home <i class="anm anm-angle-down-l"></i></a>
                  </li>
                  <li class="lvl1 parent megamenu">
                    <a href="{% url 'core:category-list' %}">Categories<i class="anm anm-angle-down-l"></i></a>
                  </li>
                  <li class="lvl1 parent megamenu">
                    <a href="{% url 'core:product' %}">Shop<i class="anm anm-angle-down-l"></i></a>
                  </li>
                  <li class="lvl1 parent dropdown">
                    <a href="#">Pages <i class="anm anm-angle-down-l"></i></a>
                  </li>
                  <li class="lvl1 parent dropdown">
                    <a href="#">Blog <i class="anm anm-angle-down-l"></i></a>
                  </li>
                  <li class="lvl1">
                    <a href="#"><b>Buy Now!</b> <i class="anm anm-angle-down-l"></i></a>
                  </li>
                </ul>
              </nav>
              <!-- End Desktop Menu -->
            </div>
            <!-- Mobile Logo -->
            <div class="col-6 col-sm-6 col-md-6 col-lg-2 d-block d-lg-none mobile-logo">
              <div class="logo">
                <a href="{% url 'core:index' %}"><img src="{% static 'assets/images/logo.svg' %}" alt="Belle Multipurpose Html Template" title="Belle Multipurpose Html Template" /></a>
              </div>
            </div>
            <!-- Mobile Logo -->
            <div class="col-4 col-sm-3 col-md-3 col-lg-2">
              <div class="site-cart">
                <a href="#" class="site-header__cart" title="Cart">
                  <i class="icon anm anm-bag-l"></i>
                  <span id="CartCount" class="site-header__cart-count" data-cart-render="item_count">2</span>
                </a>
              </div>
              <div class="site-header__search">
                <button type="button" class="search-trigger"><i class="icon anm anm-search-l"></i></button>
              </div>
            </div>
            {% if messages %}
              {% for message in messages %}
                <div class="alert alert-{{ message.tags }}">
                  <strong>{{ message }}</strong>
                </div>
              {% endfor %}
            {% endif %}
            <script>
              setTimeout(() => {
                $('.alert').alert('close')
              }, 3000)
            </script>
          </div>
        </div>
      </div>
      <!-- End Desktop viewr -->

      <!-- Mobile Menu -->
      <div class="mobile-nav-wrapper" role="navigation">
        <div class="closemobileMenu">
          <i class="icon anm anm-times-l pull-right"></i> Close Menu
        </div>
        <ul id="MobileNav" class="mobile-nav">
          <li class="lvl1 parent megamenu">
            <a href="{% url 'core:index' %}">Home</a>
          </li>
          <li class="lvl1 parent megamenu">
            <a href="{% url 'core:category-list' %}">Categories</a>
          </li>
          <li class="lvl1 parent megamenu">
            <a href="{% url 'core:product' %}">Shop</a>
          </li>
          <li class="lvl1 parent megamenu">
            <a href="about-us.html">Pages</a>
          </li>
          <li class="lvl1 parent megamenu">
            <a href="blog-left-sidebar.html">Blog</a>
          </li>
          <li class="lvl1">
            <a href="#"><b>Buy Now!</b></a>
          </li>
        </ul>
      </div>
      <!-- End Mobile Menu -->

      {% block content %}

      {% endblock %}

      <!-- Footer -->
      <footer class="footer" id="footer">
        <div class="site-footer">
          <div class="container" style="color: #333;">
            <div class="footer-bottom">
              <div class="row">
                <!-- Footer Copyright -->

                <div class="col-12 col-sm-12 col-md-6 col-lg-6 order-1 order-md-0 order-lg-0 order-sm-1 copyright text-sm-center text-md-left text-lg-left">
                  <ul class="payment-icons list--inline">
                    <li>
                      <span>Kushal store</span>
                    </li>
                  </ul>
                </div>
                <!-- End Footer Copyright -->
              </div>
            </div>
          </div>
        </div>
      </footer>
      <!-- End Footer -->

      <!-- Scoll Top -->
      <span id="site-scroll"><i class="icon anm anm-angle-up-r"></i></span>
      <!-- End Scoll Top -->

      <!-- Including Jquery -->
      <script src="{% static 'assets/js/vendor/jquery-3.3.1.min.js' %}"></script>
      <script src="{% static 'assets/js/vendor/modernizr-3.6.0.min.js' %}"></script>
      <script src="{% static 'assets/js/vendor/jquery.cookie.js' %}"></script>
      <script src="{% static 'assets/js/vendor/wow.min.js' %}"></script>
      <!-- Including Javascript -->
      <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.2/dist/umd/popper.min.js" integrity="sha384-IQsoLXl5PILFhosVNubq5LC7Qb9DXgDA9i+tQ8Zj3iwWAwPtgFTxbJ8NT4GN1R8p" crossorigin="anonymous"></script>
      <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.min.js" integrity="sha384-cVKIPhGWiC2Al4u+LWgxfKTRIcfu0JTxR+EQDz/bgldoEyl4H0zUF0QKbrJ0EcQF" crossorigin="anonymous"></script>
      <script src="{% static 'assets/js/plugins.js' %}"></script>
      <script src="{% static 'assets/js/lazysizes.js' %}"></script>
      <script src="{% static 'assets/js/main.js' %}"></script>
    </div>
  </body>
</html>